### ISSUE TITLE
Extract np URI before upload

### ISSUE THREAD

**Issue by MitchelAwesome** [peta-pico/nanodesk#10]
- is it possible to extract the URI of the newly added nanopub before uploading it to the server? 
- eg: do we know this link before upload? Or is there a way to retrieve it http://rdf.disgenet.org/nano...xk08daa

perhaps using the verbose version?

**Comment by tkuhn** [comment]
You mean directly from the TriG file? In the TriG files generated by trustyuri, the nanopub URI is on the first line after "this:". You can extract it from the first line, which is a bit of a hack. It is also output to the terminal when you run trustyuri, at least when you use the "-v" flag. It would be much easier in Java, for which we have a nanopub library. This is something that would be great to have for PHP too, but I think it shouldn't be our priority right now.
